version: "3"
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 80:80

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
